### ISSUE TITLE
convert functions for CL_objects

### ISSUE THREAD

**Issue by jakebolewski** [JuliaGPU/OpenCL.jl#1]
instead of directly passing the pointer, create convert functions which ccall uses to do automatic conversion.

**Comment by juliohm** [comment]
@jakebolewski any intention to work on this issue, does it still apply? It is from 2013 so I guess we could simply close it and focus on the ones that we can address in the near future? I am trying to revive the OpenCL.jl ecosystem. This includes cleaning the house before writing down a plan.
