### ISSUE TITLE
OpenCL 2.0 problems

### ISSUE THREAD

**Issue by nstiurca** [JuliaGPU/OpenCL.jl#100]
Using `OpenCL.Device(Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz on AMD Accelerated Parallel Processing)` (AMD's OpenCL has version 2.0), I get the following

<pre><code>julia> Pkg.test("OpenCL")
INFO: Computing test dependencies for OpenCL...
INFO: No packages to install, update or remove
INFO: Testing OpenCL
OpenCL.Platform
  > Platform Info
    Failure :: (line:-1) :: Platform Info :: fact was false
      Expression: v.major --> 1
        Expected: 1
        Occurred: 2
  > Platform Equality
Out of 25 total facts:
  Verified: 24
  Failed:   1
OpenCL.Context
  > OpenCL.Context constructor
  > OpenCL.Context platform properties
  > OpenCL.Context create_some_context
  > OpenCL.Context parsing
31 facts verified.
OpenCL.Device
  > Device Type
  > Device Equality
  > Device Info
142 facts verified.
OpenCL.CmdQueue
  > OpenCL.CmdQueue constructor
  > OpenCL.CmdQueue info
43 facts verified.
OpenCL.Macros
  > OpenCL.Macros version platform
  > OpenCL.Macros version device
12 facts verified.
OpenCL.Event
  > OpenCL.Event status
  > OpenCL.Event wait
  > OpenCL.Event callback
Test Callback
Test Callback
32 facts verified.
OpenCL.Program
  > OpenCL.Program source constructor
  > OpenCL.Program info
  > OpenCL.Program build
  > OpenCL.Program source code
  > OpenCL.Program binaries
44 facts verified.
OpenCL.Kernel
  > OpenCL.Kernel constructor
  > OpenCL.Kernel info
  > OpenCL.Kernel mem/workgroup size
  > OpenCL.Kernel set_arg!/set_args!
  > OpenCL.Kernel enqueue_kernel
74 facts verified.
INFO: ======================================================================
                              Running Behavior Tests
      ======================================================================
OpenCL Hello World Test
2 facts verified.
OpenCL Low Level Api Test
2 facts verified.
OpenCL Struct Buffer Test

signal (11): Segmentation fault
unknown function (ip: 0x7f702310d7bf)
unknown function (ip: 0x7f70230f083b)
unknown function (ip: 0x7f70230f09cf)
unknown function (ip: 0x7f7023087c99)
unknown function (ip: 0x7f7022867182)
unknown function (ip: 0x7f702286842a)
unknown function (ip: 0x7f70228685fc)
unknown function (ip: 0x7f702283ce7a)
unknown function (ip: 0x7f702286e8be)
unknown function (ip: 0x7f7022873236)
unknown function (ip: 0x7f702287a537)
unknown function (ip: 0x7f7022873c56)
unknown function (ip: 0x7f702286603e)
unknown function (ip: 0x7f702286842a)
unknown function (ip: 0x7f70228685fc)
jl_trampoline at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
anonymous at /home/nstiurca/.julia/v0.4/OpenCL/test/test_behaviour.jl:267
facts at /home/nstiurca/.julia/v0.4/FactCheck/src/FactCheck.jl:448
anonymous at /home/nstiurca/.julia/v0.4/OpenCL/test/test_behaviour.jl:246
unknown function (ip: 0x7f70228a9c4b)
unknown function (ip: 0x7f70228aa879)
jl_load at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
include at ./boot.jl:261
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
include_from_node1 at ./loading.jl:304
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
unknown function (ip: 0x7f70228956b3)
unknown function (ip: 0x7f7022894af1)
unknown function (ip: 0x7f70228a9b88)
unknown function (ip: 0x7f70228aa2f2)
unknown function (ip: 0x7f70228a9f45)
unknown function (ip: 0x7f70228aa879)
jl_load at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
include at ./boot.jl:261
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
include_from_node1 at ./loading.jl:304
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
process_options at ./client.jl:284
_start at ./client.jl:378
unknown function (ip: 0x7f701f8d5329)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
unknown function (ip: 0x401b09)
unknown function (ip: 0x4016df)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x401725)
unknown function (ip: (nil))
==============================================================================================================[ ERROR: OpenCL ]==============================================================================================================

failed process: Process(`/usr/bin/julia --check-bounds=yes --code-coverage=none --color=yes /home/nstiurca/.julia/v0.4/OpenCL/test/runtests.jl`, ProcessSignaled(11)) [0]

=============================================================================================================================================================================================================================================
INFO: No packages to install, update or remove
ERROR: OpenCL had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
</code></pre>

I'm not sure how to approach debugging/fixing this, so any ideas welcome.

PS: do we care about OpenCL support for now?

**Comment by jakebolewski** [comment]
Which runtimes support OpenCL 2.0 at the moment?

**Comment by nstiurca** [comment]
[AMD APP SDK v3.0](http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/). You can try it out on any x86_64 CPU I think (I have Intel CPU as you can see at the top of my post).

**Comment by nstiurca** [comment]
I'm curious if the segfault is reproducible for others or if something is wrong with my installation...

**Comment by vchuravy** [comment]
I just hit the same issue in #104

**Comment by rafaelcp** [comment]
Happened to me too. Then I realized that the package test file was different from the dev one. Removed the package and installed with Pkg.clone and Pkg.build. Test passed.
