### ISSUE TITLE
Installation of OpneCL in Travis

### ISSUE THREAD

**Issue by dfdx** [JuliaGPU/OpenCL.jl#103]
I'm trying to fix tests on Travis for CLBLAS.jl, which requires OpenCL to be installed. This package passes tests without any problem, but I can't grasp what in `.travis.yml` (or elsewhere) ensures OpenCL is in place. Any hints?

**Comment by vchuravy** [comment]
There is a CPU OpenCL implementation from AMD that one can install via `fglrx` https://github.com/JuliaGPU/OpenCL.jl/blob/a891eb88642610f5ed44dcaa49f6bf05e2d76639/.travis.yml#L18 .

**Comment by dfdx** [comment]
Seems like subtle changes to `.travis.yml` make build run on a legacy infrastructure somehow affecting `dkms` package and consequently `fglrx` module. Most likely I will just continue without Travis until their infrastructure is in the migration process. 

Thanks for your answer!

**Comment by vchuravy** [comment]
Yes you have to run on the old legacy infrastructure. It would be super
nice to have a script that installs and download either the Intel or AMD
opencl implementation on the new docker infrastructure.

**Comment by dfdx** [comment]
As described in JuliaGPU/CLBLAS.jl#21, I've tried AMD SDK, but they have pretty unfriendly API, so I'll continue with Intel implementation or just upload archive to whatever public storage (I hope, AMD will not be very angry with it).
