### ISSUE TITLE
CL_PLATFORM_NOT_FOUND_KHR

### ISSUE THREAD

**Issue by juliohm** [JuliaGPU/OpenCL.jl#105]
I am on Antergos Linux:

```julia
using OpenCL
OpenCL.create_compute_context()
```
>ERROR: CLError(code=-1001, CL_PLATFORM_NOT_FOUND_KHR)
 [inlined code] from /home/juliohm/.julia/v0.4/OpenCL/src/macros.jl:6
 in platforms at /home/juliohm/.julia/v0.4/OpenCL/src/platform.jl:21
 in create_some_context at /home/juliohm/.julia/v0.4/OpenCL/src/context.jl:207
 in create_compute_context at /home/juliohm/.julia/v0.4/OpenCL/src/util.jl:2

The hardware I have:

```bash
lspci
```
>00:00.0 Host bridge: Intel Corporation Skylake Host Bridge/DRAM Registers (rev 08)
00:02.0 VGA compatible controller: Intel Corporation Skylake Integrated Graphics (rev 07)
00:04.0 Signal processing controller: Intel Corporation Skylake Processor Thermal Subsystem (rev 08)
00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)
00:14.2 Signal processing controller: Intel Corporation Sunrise Point-LP Thermal subsystem (rev 21)
00:15.0 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #0 (rev 21)
00:15.1 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #1 (rev 21)
00:16.0 Communication controller: Intel Corporation Sunrise Point-LP CSME HECI #1 (rev 21)
00:1c.0 PCI bridge: Intel Corporation Device 9d10 (rev f1)
00:1c.4 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #5 (rev f1)
00:1c.5 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #6 (rev f1)
00:1d.0 PCI bridge: Intel Corporation Device 9d18 (rev f1)
00:1f.0 ISA bridge: Intel Corporation Sunrise Point-LP LPC Controller (rev 21)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-LP PMC (rev 21)
00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
00:1f.4 SMBus: Intel Corporation Sunrise Point-LP SMBus (rev 21)
3a:00.0 Network controller: Broadcom Corporation BCM4350 802.11ac Wireless Network Adapter (rev 08)
3b:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS525A PCI Express Card Reader (rev 01)
3c:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller (rev 01)

**Comment by yuyichao** [comment]
Do you have any OpenCL driver isntalled? `ls /etc/OpenCL/vendors`

**Comment by juliohm** [comment]
@yuyichao I don't have this folder here, I will check how to install the drivers and close the issue. Thank you.

**Comment by yuyichao** [comment]
IIUC Antergos Linux is Arch Based so https://wiki.archlinux.org/index.php/GPGPU#OpenCL

**Comment by juliohm** [comment]
@yuyichao I am reading the page, does OpenCL support on-board Intel graphics cards?

**Comment by yuyichao** [comment]
There's an open source driver beignet for Ivy Bridge and later hardware (older ones doesn't support OpenCL asfak). It should support SkyLake although I've seen some error on some of the OpenCL.jl tests when testing an old version a while ago.

It is available through AUR and the git version is also available in the [archlinuxcn repo](https://github.com/archlinuxcn/repo).

**Comment by juliohm** [comment]
Thank you for this very useful info, I will check this driver you mentioned in AUR.

**Comment by juliohm** [comment]
One last question: what is the idea behind using the `intel-opencl-runtime` to execute on the CPU? Let's say I want to perform FFT with OpenCL FFT instead of Julia's FFT, will it be faster? What about if I use the beignet driver that you suggested?

**Comment by yuyichao** [comment]
Beignet is GPU only and the intel proprietary driver is CPU only (on Linux).

The difference between running native code and using the OpenCL driver on CPU is roughly the difference between using gcc/clang and icc. I've seen a decent speed up using it for simple element wise array ops compare to the default blas and numpy/numpypy. I've never benchmarked it with julia though.

**Comment by yuyichao** [comment]
P.S. the comparison I did was a long time ago and the speed up might be related to eliminating the temporary arrays....

By using the OpenCL CPU driver, it can also make use of all the features the CPU provides, which can make a big difference if your julia is not compiled with `-C native`.

**Comment by juliohm** [comment]
Thank you for all the answers @yuyichao, they are really helpful. I will try to use the GPU with Beignet first and then try the CPU with the Intel driver. My Julia was compiled from Github, I didn't touch the Makefiles though. I will keep the `-C native` option in mind.

**Comment by yuyichao** [comment]
Default source compilation should be using the native arch. (And if you are just comparing fft, this shouldn't matter since fftw can detect these at runtime too).

**Comment by juliohm** [comment]
You mean fftw will be as fast as using the OpenCL FFT with the Intel driver on the CPU? I will only try Beignet then.

**Comment by yuyichao** [comment]
Well, it will depend on which one is better optimized. OpenCL does come with additional overhead so I would guess OpenCL FFT shouldn't be much (if any) faster... It's hard to tell without actually benchmarking it though (didn't find any with a brief google search). (If you find OpenCL FFT to be significantly faster, you can probably report it to fftw ;-p ).

As a side note, in my experience, the Intel CPU driver is the one that is easiest to setup so I recommend trying it to make sure everything else is working.

**Comment by juliohm** [comment]
Thank you! I will follow all your suggestions.

**Comment by gaozhang** [comment]
Hello, I'm a new user and I have the same problem today. Have you solved it yet?
