### ISSUE TITLE
Apparent OpenCL.read error

### ISSUE THREAD

**Issue by ericproffitt** [JuliaGPU/OpenCL.jl#110]
Consider the code: 

```
using OpenCL
device, context, queue = OpenCL.create_compute_context()

a = rand(Float32, 125356789)
abuf = OpenCL.Buffer(Float32, context, (:r, :copy), hostbuf=a)
b = OpenCL.read(queue, abuf)
isapprox(a, b)
```

You can clearly see that upon reading `abuf` back into host memory, that the last 50 or so coordinates are now zeroed out.  The vector `a` is about half a gigabyte, which is well within both my host and device's memory, what is going on here?  Is this something caused by the wrapper or is it a bug in OpenCL itself?

**Comment by yuyichao** [comment]
Works for me. What driver are you using and can you reproduce with C?

**Comment by esproff** [comment]
@yuyichao 

By driver version do you  mean what version of OpenCL?  I'm using OpenCL 1.2 on an Intel HD Graphics 4000 with 1536MB, unfortunately I don't know C well enough to try reproducing in C.

**Comment by yuyichao** [comment]
No I mean what driver you are using and on what platform.

**Comment by esproff** [comment]
@yuyichao 

I don't really know what a driver is TBH or how to find it, I typed `device[:driver_version]` and it said 1.2.  I'm on a macbook pro mid-2012 if that helps.  Searching online and on my mac system profile and so far haven't found driver info.

**Comment by esproff** [comment]
@yuyichao 

Ok so I think I may have found it, here is the info on the driver I think:

  Version:	2.7.0
  Last Modified:	4/19/16, 9:16 PM
  Bundle ID:	com.apple.driver.Intel82574L
  Loaded:	No
  Get Info String:	2.7.0, Copyright Apple, Inc. 2009-2015
  Obtained from:	Apple
  Kind:	Intel
  Architectures:	x86_64
  64-Bit (Intel):	Yes
  Location:	/System/Library/Extensions/IONetworkingFamily.kext/Contents/PlugIns/Intel82574L.kext
  Kext Version:	2.7.0b1
  Loadable:	Yes
  Dependencies:	Satisfied
  Signed by:	Software Signing, Apple Code Signing Certification Authority, Apple Root CA

**Comment by esproff** [comment]
Has anyone be able to reproduce this yet?  It's really frustrating.

**Comment by vchuravy** [comment]
Sorry, I don't have a mac available for testing. I will see if I can reproduce this with travis.

**Comment by vchuravy** [comment]
@esproff Are you using Julia v0.4?

**Comment by esproff** [comment]
@vchuravy Yes I'm using Julia v0.4.6.

**Comment by vchuravy** [comment]
```
for platform in OpenCL.platforms()
    @show platform
    @show OpenCL.available_devices(platform)
end
```

**Comment by esproff** [comment]
@vchuravy 

I ran your code and here is the output:

```
platform = OpenCL.Platform('Apple' @0x000000007fff0000)
OpenCL.available_devices(platform) = [OpenCL.Device(Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz on Apple @0x00000000ffffffff),OpenCL.Device(HD Graphics 4000 on Apple @0x0000000001024400)]
```

**Comment by vchuravy** [comment]
Can you run your code on the CPU device? OpenCL implementation are all over
the board and I wouldn't be surprised if there is a problem with the
combination of Apple + Intel GPU.

**Comment by esproff** [comment]
@vchuravy 

Thanks for getting back to me so quickly, apologies for the delay in getting back to you, it took me a bit to figure out how to set my device and context to my CPU.  So I set them to the CPU, and ran my code example above, and it works fine on the CPU, no problems.
