### ISSUE TITLE
How to set OpenCL.api.clSetKernelArg arguments

### ISSUE THREAD

**Issue by esproff** [JuliaGPU/OpenCL.jl#115]
So I'm trying to initialize a local array in my kernel with a length which is only known at runtime.  Here is what I'm working with:

```
using OpenCL

const testcpp =
"""
kernel void
test(local float *A)
{
}
"""

device, context, queue = OpenCL.create_compute_context()

program = OpenCL.Program(context, source=testcpp) |> OpenCL.build!
kernel = OpenCL.Kernel(program, "test")

Abuf = OpenCL.Buffer(Float32, context, (:rw, :copy), hostbuf=rand(Float32, 5))

OpenCL.api.clSetKernelArg(kernel, 0, 5 * 4, Abuf)

OpenCL.call(queue, kernel, 1, nothing, C_NULL)
```

It should be some rearrangement of this code, I'm not really sure, I tried copying the examples on stack exchange basically verbatim, but I can't get it to work, I'm not sure in what order the arguments to `clSetKernelArg` should go in.

If I don't use `clSetKernelArg` at all I can actually work with the local array inside the kernel but it just seems to be filled with unreferenced values and it basically has no length, you can access any index and it will just grab the value at that local memory address, w/e it is.

**Comment by vchuravy** [comment]
Issuing `OpenCL.call` will reset the arguments https://github.com/JuliaGPU/OpenCL.jl/blob/release-0.4/src/kernel.jl#L168.

If you want to manually set the arguments you have to use `enqueue_kernel` or you can just pass the arguments to `call`

**Comment by esproff** [comment]
Ok I figured this out with the help of vchuravy's link.  Basically there's a `OpenCL.LocalMem` type which you can initialize with a size.  You can then use these as arguments to `OpenCl.call`.
