### ISSUE TITLE
OpenCL / cl module names

### ISSUE THREAD

**Issue by lawless-m** [JuliaGPU/OpenCL.jl#117]
Hi,

Julia 0.4.6 / OpenCL v0.4.1

to get https://github.com/JuliaGPU/OpenCL.jl/blob/master/examples/performance.jl to work

I  had to change cl. to OpenCL.

I see in the source they are nested modules

module OpenCL

export cl
module cl
...
end # cl
end # module

but this is the behavior I see

julia> using OpenCL

julia> cl
ERROR: UndefVarError: cl not defined

julia> OpenCL.cl
ERROR: UndefVarError: cl not defined

julia>

When it runs I get

> julia performance.jl

Size of test data: 32 MB
Julia Execution time: 0.0450 seconds
====================================================
Platform name:    Intel(R) OpenCL
Platform profile: FULL_PROFILE
Platform vendor:  Intel(R) Corporation
Platform version: OpenCL 1.2
----------------------------------------------------
Device name: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
Device type: cpu
Device mem: 8100 MB
Device max mem alloc: 2025 MB
Device max clock freq: 3300 MHZ
Device max compute units: 4
Device max work group size: 1024
Device max work item size: (1024,1024,1024)
Execution time of test: 0.0103 seconds
INFO: Result norm: 0.0
====================================================
Platform name:    Intel(R) OpenCL
Platform profile: FULL_PROFILE
Platform vendor:  Intel(R) Corporation
Platform version: OpenCL 1.2
----------------------------------------------------
Device name: Intel(R) HD Graphics 4600
Device type: gpu
Device mem: 1784 MB
Device max mem alloc: 446 MB
Device max clock freq: 400 MHZ
Device max compute units: 20
Device max work group size: 512
Device max work item size: (512,512,512)
Execution time of test: 0.0088 seconds
INFO: Result norm: 0.0

**Comment by vchuravy** [comment]
Julia v"0.4" is supported on the release-0.4 branch. The code on master is for Julia v"0.5".

See https://github.com/JuliaGPU/OpenCL.jl#currently-supported-julia-versions and NEWS.md

**Comment by lawless-m** [comment]
my mistake, I do apologise
