### ISSUE TITLE
Why wrap OpenCL.jl in two modules?

### ISSUE THREAD

**Issue by esproff** [JuliaGPU/OpenCL.jl#118]
Is there a reason everything in the OpenCL.jl file is now wrapped in `module OpenCL` _and_ `module cl`?

Now for non-exported functions you have to write, for example, `OpenCL.cl.Buffer`, instead of just `OpenCL.Buffer`.

**Comment by vchuravy** [comment]
What I noticed was that we were writing
```
import OpenCL
const cl = OpenCL
cl.Buffer
```

now you can just write
```
using OpenCL # This will only bring `cl` into your namespace
cl.Buffer
```

**Comment by esproff** [comment]
@vchuravy Ah how did I not realize that I could just do that, silly oversight by me, ok fair enough, thanks.
