### ISSUE TITLE
Running tests with GPU on Travis CI

### ISSUE THREAD

**Issue by juliohm** [JuliaGPU/OpenCL.jl#121]
My package uses OpenCL as an optional dependency: https://github.com/juliohm/ImageQuilting.jl/blob/master/src/ImageQuilting.jl#L28-L32. Some users will have it installed and in that case I would like to test the part of my code that is using the GPU. Currently I have zero coverage for GPU code because I don't know how to set up Travis properly.

Can you help me setting up Travis to run tests on GPU? Is it possible to do it only when a GPU is detected?

**Comment by vchuravy** [comment]
The Travis in general doesn't have GPUs. The good thing about OpenCL is that you can use a CPU implementation of OpenCL.
Travis on Mac already comes with one and for Linux you can install several different ones. I would personally recommend POCL, the proprietary ones (Intel,Amd) are tricky to install on Travis.

We are using the AMD one for our testing see: https://github.com/JuliaGPU/OpenCL.jl/blob/783774e452b71a0eb6a4d26c3208dd2f0a564083/.travis.yml

**Comment by juliohm** [comment]
Thanks @vchuravy , how would you install POCL in the Linux machine? Just do something like:

```bash
before_install:
- sudo apt-get install pocl
```

Why are you using AMD if POCL is easier to setup?

**Comment by vchuravy** [comment]
POCL is a bit more experimental in nature and not all the features we are supporting are supported by them. 
I think the ubuntu on travis is so horribly outdated that the won't have a modern version of pocl in the repo. Best to build it yourself.

**Comment by juliohm** [comment]
Can I copy the AMD scripts in OpenCL.jl in case I figure out that POCL from the repos is not enough? I am only using CLFFT features in my package.

**Comment by vchuravy** [comment]
Sure thing.

**Comment by juliohm** [comment]
@vchuravy suppose I have a function that does the GPU setup on my package: https://github.com/juliohm/ImageQuilting.jl/blob/master/src/utils_gpu.jl#L22-L45

I can run tests locally on my machine because I have the GPU properly configured with the driver and etc. Now, suppose I want to test the code on Travis without a GPU available, but on any device visible by POCL. Would it be safe to just remove the symbol `:gpu` from the `cl.devices()` call and push it to Travis?

I am expecting that on Travis the first Device found will be a CPU, whereas in other users' machines it will be a GPU with priority 1) NVIDIA, 2) AMD and 3) Intel. Makes sense?

**Comment by vchuravy** [comment]
Sadly there is no such guarantee :(, best thing you can do is

```
devs = cl.devices(:gpu)
if length(devs) == 0
   devs = cl.devices()
end
dev = first(devs) 
```

**Comment by juliohm** [comment]
Thank you @vchuravy , I will consider doing something like that. It is hard to make sure the GPU is properly installed and at the same time test on Travis and get 100% coverage.

**Comment by juliohm** [comment]
@vchuravy do you know if there is any way to interact with the Travis prompt before committing changes to it?

**Comment by vchuravy** [comment]
Not that I am aware of...
