### ISSUE TITLE
CommandLine Error: Option 'help-list' registered more than once!

### ISSUE THREAD

**Issue by juliohm** [JuliaGPU/OpenCL.jl#125]
Whenever I try to use `OpenCL.jl`, including its test suite, I get the following error:

```julia
using OpenCL
cl.create_some_context()
```
>: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options

Currently, I cannot use my GPU. Tried to checkout the master branch, but the problem is still there. Below are more details about the environment:

>Julia Version 0.5.1-pre+31
Commit 6a1e339ac* (2016-11-17 17:50 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

> - OpenCL                        0.5.0

**Comment by vchuravy** [comment]
Is this a different system from: https://github.com/JuliaGPU/OpenCL.jl/issues/122#issuecomment-267299813?

**Comment by juliohm** [comment]
@vchuravy no, the same system, should I rename that other issue instead and close this one?

**Comment by vchuravy** [comment]
keep it open for now.

The error you are seeing is odd, since we never call llvm from the command line, but it might be a collision of different versions of llvm being used by Julia and beignet/intel driver.

**Comment by juliohm** [comment]
@vchuravy I don't know if it is related, but recently `libcl` was replaced by `ocl-icd` in Arch Linux.

**Comment by juliohm** [comment]
@vchuravy any idea on how to solve this issue? We are about to submit a paper regarding our Julia package, however; its GPU features are currently not working in my workstation because of this issue.

**Comment by vchuravy** [comment]
I don't have a system that supports Beignet currently (and iirc that is the OpenCL implementation you are using?).
From recent discussion it seems that you might have multiple LLVM version in-memory and they are not name-spaced correctly
and thus conflict with each other.

The thing you might do right now is to make sure that both Beignet and Julia use the same LLVM. This will involve
1. Make sure that your system LLVM is 3.7+
2. Rebuild Julia 0.5.0 with USE_SYSTEM_LLVM=1
3. Rebuild Beignet 1.2 (that is the current stable version) and use the same LLVM

Also note that you are not supposed to build Julia from `release-0.5` branch since it sees less testing.
An alternative would be to keep Julia as it is right now and try to build Beignet against the Julia LLVM, 
this might be a tad more complex and I have not tried that yet.

**Comment by juliohm** [comment]
Thank you @vchuravy what is a good way to check what LLVM version Beignet is linking?

Below you can find more details about the system:

# System's LLVM

>$ pacman -Qi llvm-libs 
Name            : llvm-libs
Version         : 3.9.1-2
Description     : Low Level Virtual Machine (runtime libraries)
Architecture    : x86_64
URL             : http://llvm.org/
Licenses        : custom:University of Illinois/NCSA Open Source License
Groups          : None
Provides        : None
Depends On      : gcc-libs  zlib  libffi  libedit  ncurses
Optional Deps   : None
Required By     : clang  llvm  mesa  mesa-vdpau
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 45.21 MiB
Packager        : Evangelos Foutras <evangelos@foutrelis.com>
Build Date      : Sat 31 Dec 2016 05:58:42 AM PST
Install Date    : Mon 02 Jan 2017 04:58:32 AM PST
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature

# Julia's LLVM:

>julia> versioninfo()
Julia Version 0.5.1-pre+31
Commit 6a1e339ac* (2016-11-17 17:50 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

Maybe this is enough information to conclude that I need to recompile Julia, do you agree?

**Comment by vchuravy** [comment]
Yeah the easiest thing might be to recompile Julia to use the system LLVM, but I forgot if we have LLVM 3.9  support on 0.5. We recently upgraded to 3.9.1 for 0.6.

**Comment by juliohm** [comment]
I just realized that Julia is in Arch repos, I will give it a try first before compiling it myself. This will also in theory keep LLVM and Julia synced in future releases (hopefully).

**Comment by juliohm** [comment]
Unfortunately the version in the Arch repos is also linking with LLVM 3.7.x.

I understood that Julia v0.5 doesn't support LLVM 3.9.x and that I need to have Beignet using the same LLVM version than Julia does. How can I check Beignet's LLVM version?

This is the output of ldd on Beignet's libcl.so:

>$ ldd libcl.so 
	linux-vdso.so.1 (0x00007ffeef9b2000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f6b5b80d000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f6b5b5fb000)
	libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x00007f6b5b3f5000)
	libdrm_intel.so.1 => /usr/lib/libdrm_intel.so.1 (0x00007f6b5b1d1000)
	libdrm.so.2 => /usr/lib/libdrm.so.2 (0x00007f6b5afc1000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f6b5ada4000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f6b5ab9e000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f6b5a816000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f6b5a512000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f6b5a174000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f6b59f4b000)
	libpciaccess.so.0 => /usr/lib/libpciaccess.so.0 (0x00007f6b59d41000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x000055700c21c000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f6b59b28000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f6b59924000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f6b5971e000)

**Comment by vchuravy** [comment]
You could try using `downgrade`[1,2] to downgrade LLVM to 3.7.1 and then rebuild Julia with `USE_SYSTEM_LLVM=1`.

[1] https://aur.archlinux.org/packages/downgrader/
[2] https://aur.archlinux.org/packages/downgrade/

**Comment by sjkelly** [comment]
I am getting this issue with GLVisualize as well:
```
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: AMD A10-7850K Radeon R7, 12 Compute Cores 4C+8G
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Steamroller)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, bdver3)
```

After some digging I found this comment/patch that may be of help: https://bugs.freedesktop.org/show_bug.cgi?id=89325#c1

**Comment by juliohm** [comment]
@vchuravy can you confirm this issue won't be fixed in Julia v0.5? Is it related to the Julia version at all?

**Comment by vchuravy** [comment]
Yes. Since the problem is not with Julia itself, but with the interaction between different versions and builds of LLVM have. There is no immediate good solution and I don't know if there is anything we actually can do from the Julia side (JuliaLang/julia#12644 tracks that from the Julia side). This will need to be fixed with LLVM or on the packaging side of drivers (they could link LLVM statically.)

**Comment by juliohm** [comment]
This problem is solved in Julia v0.6, awesome. Closing it.

**Comment by vchuravy** [comment]
This will become an issue again once the llvm versions start diverging again...

**Comment by ihnorton** [comment]
If this happens again, try `dlopen`ing the library with `Libdl.RTLD_DEEPBIND` (but be sure you do that for the very first dlopen of a given .so path -- the first load option dominates)
