### ISSUE TITLE
cl.call not found. Was the name of the function changed?

### ISSUE THREAD

**Issue by davidbp** [JuliaGPU/OpenCL.jl#150]
Hello,
I was trying to execute the notebook `Fractals.ipynb` from your examples but I got the following error:

```julia
cl.call(queue, k, length(q), nothing, q_buff, o_buff, UInt16(maxiter))
UndefVarError: call not defined

Stacktrace:
 [1] include_string(::String, ::String) at ./loading.jl:522
```

It seems `cl.call`  is not found.

**Comment by davidbp** [comment]
@SimonDanisch, @vchuravy  I have seen that

```julia
cl.call(queue, k, length(q), nothing, q_buff, o_buff, UInt16(maxiter))
```
Could be simply written as

```julia
queue( k, length(q), nothing, q_buff, o_buff, UInt16(maxiter))
```

Do you want me to update the notebooks with the correct syntax and make a pull request? 

The notebooks in the current OpenCL.jl version do not seem to work.

**Comment by SimonDanisch** [comment]
That would be great :)

**Comment by davidbp** [comment]
I have done a test here:

https://github.com/davidbp/learn_julia/blob/master/GPU_compute/OpenCL/julia_set_fractal.ipynb

Maybe you could try to execute it and see if you get "similar results". The results are quite different from the ones Simon showed at the juliacon.If I remember correctly the GPU implementation was even a bit slower than the CPU implementation and the reasoning was that it was just a simple integrated GPU. In my case even with the intel HD 4000 the results are much better than with the core i7. Maybe I am not benchmarking the exact same thing.

**Comment by SimonDanisch** [comment]
Without looking at the notebook (i'm on my phone), did you synchronize?

**Comment by davidbp** [comment]
I measured execution time as in the original notebook. That is:

```julia
device = cl.devices()[1]
    OpenCL.Device(Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz on Apple @0x00000000ffffffff)
@time m = julia_opencl(q, 1000, device);
      10.560125 seconds (169 allocations: 32.022 MiB, 0.05% gc time)
```

```julia
device = cl.devices()[2]
     OpenCL.Device(HD Graphics 4000 on Apple @0x0000000001024400)
@time m = julia_opencl(q, 100, device);
      1.408798 seconds (169 allocations: 32.022 MiB, 0.27% gc time)
```

Since `m` contains the result of the array (the fractal) it seems a valid measurement.

**Comment by SimonDanisch** [comment]
actually, this does look normal to me..  if i reported different measurements, its possibly because i was on linux with bad driver support for the hd4000!

**Comment by davidbp** [comment]
I have tested and updated the notebooks

https://github.com/davidbp/learn_julia/blob/master/GPU_compute/OpenCL/julia_set_fractal.ipynb

https://github.com/davidbp/learn_julia/blob/master/GPU_compute/OpenCL/Mandelbrot_fractal.ipynb

If you want you can copy them

**Comment by davidbp** [comment]
@SimonDanisch @vchuravy  what do you think?
Now the device used is more clear and the comparison between CPU and GPU is more informative of the speedup you might get.

**Comment by vchuravy** [comment]
Great thank you
