### ISSUE TITLE
updated notebook example for fractals, but the kernel doesn't produce correct results

### ISSUE THREAD

**Issue by rabarar** [JuliaGPU/OpenCL.jl#171]
I've modified the Notebook to be compatible with Julia 1.0.1 but the results aren't compatible - I'm BRAND NEW to Julia - perhaps I'm missing something - Ive attached the modified notebook for reference.

[fract.ipynb.json.zip](https://github.com/JuliaGPU/OpenCL.jl/files/2530794/fract.ipynb.json.zip)

**Comment by tkluck** [comment]
I ran into this just now as well. This is probably too late to be useful for you, but for others who find this issue: I solved it by replacing `Complex64` in the old code by `ComplexF32`. I haven't gone back far enough in Julia's history, but my guess is that `Complex64` used to be a `Complex{Float32}` (for 64 bits in total). With that change, I've been able to reproduce the Fractal example.
