### ISSUE TITLE
Support for OpenCL floatN and doubleN types

### ISSUE THREAD

**Issue by vchuravy** [JuliaGPU/OpenCL.jl#18]
It would be nice if OpenCL.jl would be able to support the halfN, floatN and doubleN types that OpenCL provides on Julias side.

Currently it is possible to initialize a double4 buffer with

``` julia
    test_buff = cl.Buffer(Float64, ctx, :rw, Ndim * Mdim * 4)
```

But working with that data on Julias side is a hassle.

**Comment by nstiurca** [comment]
One possible use case for OpenCL's `float2`/`float4` is to represent complex numbers or quaternions. Likewise, `uchar3`/`uchar4` often represent RGB/RGBA pixels. We should consider if there is a clean way to map between eg Julia's `Complex` <--> `half2`/`float2`/`double2`, or Julia's `Quaternion` <--> `float4`, or mapping to `Colors.RGB`, etc.

**Comment by nstiurca** [comment]
Also, no reason to limit to float/double support. We should also support all integer types, as well as half if the OpenCL device supports it.
