### ISSUE TITLE
Cannot create a buffer with a size than exceeds a UInt32

### ISSUE THREAD

**Issue by herzfeldd** [JuliaGPU/OpenCL.jl#183]
I am unable to create a buffer with a size that exceeds the size of a `UInt32` due to an `InexactError` in `buffer.jl:126` (it currently casts the number of bytes of the buffer to a `cl_uint`). I should be able to allocate a buffer larger than this on my card as `device[:address_bits]` is 64. 

I don't think there would be an issue changing this parameter to type `cl_ulong`, but I have not gone through the code in great detail.

**Comment by SimonDanisch** [comment]
Your best chance to get this into OpenCL.jl would be to try out the change and make a PR ;)
