### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by juliohm** [JuliaGPU/OpenCL.jl#199]
The OpenCL_jll build is failing on Windows. One of the OpenCL maintainers successfully fixed the build by [disabling a feature](https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/186) that I think may be important for Windows users. He mentioned that an alternative solution would be to upgrate the version of mingw in BinaryBuilder.jl. More details [here](https://github.com/KhronosGroup/OpenCL-SDK/issues/58#issuecomment-1270883249).

**Comment by WilliamSoCreat** [comment]
why dont you use wsl2 ?
its good and i like it

**Comment by ufechner7** [comment]
Is this issue fixed? Does the current version work on Windows now that #186 is merged?

**Comment by maleadt** [comment]
Implemented in https://github.com/JuliaPackaging/Yggdrasil/pull/9224
