### ISSUE TITLE
PoCL as fallback driver

### ISSUE THREAD

**Issue by juliohm** [JuliaGPU/OpenCL.jl#200]
We would like to automatically install drivers for end-users. As far as I understand, [PoCL](http://portablecl.org/) is a recent attempt to provide a portable driver that works with any device (NVIDA, AMD, Intel…). The plan is to create a PoCL_jll that gets installed as a fallback driver. That would save users from cryptic runtime error messages. Can anyone help here building the PoCL_jll?

**Comment by maleadt** [comment]
Implemented in https://github.com/JuliaGPU/OpenCL.jl/pull/210
