### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by nowozin** [JuliaGPU/OpenCL.jl#28]
Thanks for the great OpenCL package, for me it works out of the box on Windows 8.1 (using CUDA) and Ubuntu 14.04 (using Intel OpenCL and the AMD APP SDK).

I have used PyOpenCL before for GPU image processing and a typical code to create a RGBA image buffer on the device using PyOpenCL is this

``` python
    iform = cl.ImageFormat(cl.channel_order.RGBA, cl.channel_type.UNSIGNED_INT8)
    im_buffer = im.tostring()
    cl_img = cl.Image(context, cl.mem_flags.READ_ONLY |
        cl.mem_flags.COPY_HOST_PTR, iform, self.im.size, None, im_buffer)
```

I have not had success in trying to load an image onto the device using OpenCL.jl.  I can create the image format object using

``` julia
using Images
import OpenCL
const cl = OpenCL

function load_image(image_pathname)
    img = imread(image_pathname)
    img = convert(Array, img)
    img
end

img = load_image("test.jpg")

device = first(cl.devices())
iform = cl.CL_image_format(cl.CL_RGBA, cl.CL_UNSIGNED_INT8)
```

But I cannot find an image class as in PyOpenCL.

If it is already supported, can you create a simple example that loads an image onto the device, please?

**Comment by nowozin** [comment]
Hi,

thanks for all your work so far.  Since some time has passed, is an Image type still on the radar?
(This is most useful for fast hardware-assisted linear interpolation as doing so manually without using the GPU texture units is significantly slower.)

Thanks for considering,
Sebastian

**Comment by vchuravy** [comment]
@nowozin I have not been doing a lot of work in OpenCL recently (and I believe Jake is in a similar situation), so development of OpenCL.jl has been stagnant. I am planning to make sure that it works under Julia v0.4 (as soon as development for that has settled down), but otherwise I have no plans on working on big features in the foreseeable future.

If you are willing you are willing to offer help that would be most welcome.

**Comment by stillyslalom** [comment]
I'm also interested in hardware interpolation of images (as seen [here](https://gist.github.com/inducer/c83d58aa1ea3640b16ee) in PyOpenCL), but I'm not sure where to start. Has anyone taken a crack at this yet?

**Comment by timholy** [comment]
Not that I know of, but now that GPU support in Julia seems to be spectacular (and still getting better), I'm excited about this. But I'm not qualified to advise you how to start. Maybe https://github.com/JuliaGPU/GPUShowcases.jl would offer some useful clues? My impression is that this doesn't need to be OpenCL-specific, that the Julia infrastructure can support multiple backends.

**Comment by vchuravy** [comment]
@SimonDanisch last worked on supporting the OpenCL definition of images, but I don't think any of the attempts ever got to a point.
I would be excited to see if we can make Images.jl and OpenCL.jl play nicely with each other.

**Comment by juliohm** [comment]
This issue dates back to 2014 and it seems that the discussion got mixed between OpenCL and OpenGL efforts. I will close the issue as part of house cleaning and an attempt to maintain a lightweight OpenCL.jl package for a recent version of the language.
