### ISSUE TITLE
Splitting up API 

### ISSUE THREAD

**Issue by vchuravy** [JuliaGPU/OpenCL.jl#40]
To address one of my concerns in #39 I would propose to only load the OpenCL API depending on the maximum version available on the machine.

So I would change the api loading in the following way.
- bootstrap.jl -> Minimum bases for finding all platforms and checking the supported version of the   platform. 
- api/opencl10.jl contains all undepreciated api calls from version 1.0
- api/opencl10-depreciated11.jl contains all api calls from version 1.0 that were depreciated in version 1.1
- api/opencl10-depreciated12.jl contains all api calls from version 1.0 that were depreciated in version 1.2
- api/opencl11.jl includes opencl10.jl
- etc. pp.

``` Julia
module OpenCL
    include ("bootstrap.jl")

    global OPENCL_VERSION :: VersionNumber

    function __init__()
        global OPENCL_VERSION = maximum(map(cl.opencl_version, cl.platforms())

        if OPENCL_VERSION == v"1.2"
            include("api/opencl12.jl")
        elseif OPENCL_VERSION == v"1.1"
            include("api/opencl11.jl")
            include("api/opencl11-depreciated12.jl")
        elseif
            include("api/opencl10.jl")
            include("api/opencl10-depreciated11.jl")
                include("api/opencl10-depreciated12.jl")
        end
    end

    include("...everything else")
end
```

Since we use macros to generate the api calls a include in a function actually works and adds the generated function i the correct scope.

This proposal would also make it easier to add OpenCL 2.0

**Comment by juliohm** [comment]
I don't know if it is relevant to the discussion that was started here, but I recently built the OpenCL_jll wrapper with BinaryBuilder.jl and am trying to refactor this package to use it instead. Would that be a good path forward?
