### ISSUE TITLE
Cssize_t and Julia 0.4

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGPU/OpenCL.jl#63]
Hi, 
I just recently noted, that the conversion in types.jl:143 is wrong, as Julia now throws an error, if something overflows.
`cl_context_properties(x) = convert(CL_context_properties, x)`
Should be rather something like this:
`cl_context_properties(x::Ptr{Void}) = reinterpret(CL_context_properties, x)` or in 0.4
`cl_context_properties(x::Integer) = uint64(x) % CL_context_properties`
As intptr_t actually allows for overflow, as long as it can be transferred back to the same Ptr{Void}.
I haven't opened a pull request, as I first want to discuss this, and search for further similar issues.
Best,
Simon

**Comment by jakebolewski** [comment]
Do you have a use case where C overflow behavior is actually needed?

**Comment by SimonDanisch** [comment]
Yes! To create a OpenGL interop  context, you need the Ptr{Void} handle returned by `wglGetCurrentDC`, which is sometimes pretty close to `typemax(uint64)`. As it needs to be converted to CL_context_properties( -> int64) it'll throw an  `InexactError()`. 
This can lead to very subtle, non reproducible bugs. I had the pleasure to debug this without a good stack trace, throwing an error just every ~third time, because its coincided with some julia line number bug. 
This is pretty nasty and if we don't want to have unpredictable errors popping up, we should hunt down similar cases.

From stdint:
````
Integer type capable of holding a value converted from a void pointer and then be converted back to that type with a value that compares equal to the original pointer.
```
Which is mostly likely the convention other interfacing libries will stick to, which means throwing an error for overflow is plain wrong.

By the way, `Base.sizeof(mem::CL_mem)` in memory.jl:14 should be flagged as unsafe!
If someone imports OpenCL and tries to find out the size of a Ptr{Void}, it will simply segfault, which is really not that nice, as it changes the behavior of other libraries.

**Comment by jakebolewski** [comment]
Thanks @SimonDanisch for providing a bit of context.  I fixed the last issue. The method should have been defined for the object, not the typealias.

You are right that many C-libraries will rely on the overflow behavior here.  I think that this is more of a Julia issue than it is a OpenCL issue.  Can you file a Julia issue for the overflow checking of the C typealiases.

Thanks for being brave and using this on v0.4...

**Comment by SimonDanisch** [comment]
Oh you're right... This should actually be handled by Julia. But I wonder, how one could handle this in a generic way, since Cssize_t is just a type alias...

**Comment by jakebolewski** [comment]
Well the intent would be that this would not be a typealias but a different
bitstype with its own semantics.  It probably won't go over well so it
would be nice if you could give a nice description of the problem you are
having (that OpenGL assumes this behavior). You would be the best person to
describe the problem as I don't think I could articulate the OpenGL
behavior as well as you.

Overall, I'm unsure it is worth the extra complexity but it is certainly
worth discussing.  Doing this correctly would be a bit tricky as ccall
calls convert under the hood (and julia does implicit conversion of values
for many methods) so this would touch a large part of OpenCL.jl.  I think
for now it is probably best to use 0.3 if you have to do something serious.

**Comment by SimonDanisch** [comment]
I see, well then I'll open an issue tomorrow!
I'm trying to build some infrastructure, which is at most ready, when 0.4 is out. So I better run into these  bugs early, instead of letting them accumulate. Also I need some features from 0.4 ;)
The project is very, very early in the process, but it might also be interesting for you: https://github.com/SimonDanisch/UberSignals.jl
I plan to accumulate use cases and design ideas in the next weeks, and try to get people exited for the idea.
The plan is, to have an event system, which can process large datasets/time-series and visualize them without much overhead.

**Comment by jakebolewski** [comment]
Cool!  Looking forward to your progress.

**Comment by jakebolewski** [comment]
@SimonDanisch can you confirm that this fixes your original problem?

**Comment by SimonDanisch** [comment]
Seems to work! =)

**Comment by jakebolewski** [comment]
Thanks for tracking down the bug!
