### ISSUE TITLE
Bug in examples\hands_on_opencl\ex08\matmul.jl

### ISSUE THREAD

**Issue by ssouyris** [JuliaGPU/OpenCL.jl#64]
Hi, thanks for the package!

I think that the file examples\hands_on_opencl\ex08\matmul.jl has the following bug:

It says:

``` julia
#--------------------------------------------------------------------------------
#OpenCL matrix multiplication ... C row per work item, A row pivate, B col local 
#--------------------------------------------------------------------------------
kernel_source = open(readall, joinpath(src_dir, "C_block_form.cl"))
...
    evt = cl.call(queue, mmul, (Ndim,), (int(ORDER/16),),
                  int32(Mdim), int32(Ndim), int32(Pdim),
                  d_a, d_b, d_c, localmem1, localmem2)
```

it should be:

``` julia
#--------------------------------------------------------------------------------
#OpenCL matrix multiplication ... blocked
#--------------------------------------------------------------------------------
kernel_source = open(readall, joinpath(src_dir, "C_block_form.cl"))
...
    evt = cl.call(queue, mmul, (Ndim,Mdim), (blocksize,blocksize),                        
                  int32(Mdim), int32(Ndim), int32(Pdim),
                  d_a, d_b, d_c, localmem1, localmem2)
```

Also a suggestion. In the examples, the matrices are stored in row-major order. As you do in python numpy. So that `A[i,k] = h_A [ (i-1)*Ndim + k]`  (if the first index is 1)

But in julia, the arrays are sorted in column-major order. So `A[i,k] = h_A[i + (k-1)*Ndim]`.  

In the examples there is not problem because the matrices are NxN and store the same values (AVAL, BVAL). But with different dimensions and/or stored values, it could be a problem. 

To work nicely with the julia reshape function back and forth, the arrays in the OpenCl kernels should be read `h_A [i + k*Ndim]` (first index is 0), instead of `h_A[i*Ndim + k]`

Does it make sense?

Note: the github formatting is taking out a couple of [ ] parenthesis 

~Edit(@vchuravy) added github formatting

**Comment by jakebolewski** [comment]
@ssouyris thanks for the report!   I'll try to push a fix soon, PR's always welcome as well :-)

**Comment by ssouyris** [comment]
Sure, thanks! I'd glad to contribute. I'll PR to fix the detail in ex08\matmul.jl, and add a new more general matmul.jl adapted to the julia array column-major order.
