### ISSUE TITLE
Remaining compatibility issues with OpenCL.jl and Julia v0.4

### ISSUE THREAD

**Issue by klkeys** [JuliaGPU/OpenCL.jl#73]
Hello,

Many thanks for developing this package! I have found it quite useful.

Now that Julia v0.4 has been released, will OpenCL.jl move to the v0.4 environment? I noticed several deprecation warnings when loading OpenCL.jl into Julia v0.4.

**Comment by SimonDanisch** [comment]
No one got around to it yet ;) since most deprecation warnings are easy to fix, feel free to submit a pull request!
Best, 
Simon

**Comment by klkeys** [comment]
It would seem that my question was premature. I think that I was not operating with the master branch of OpenCL.jl. The master branch addresses the v0.4 compatibility issues already! My apologies for the false alarm. I move to close this issue...

**Comment by jakebolewski** [comment]
@klkeys do we need to tag a new release?  I thought we already did this but 0.4 was only released recently.

**Comment by vchuravy** [comment]
@jakebolewski our last relese is from August and the 0.4 fixes came in September
