### ISSUE TITLE
Serialization of OpenCL pointers

### ISSUE THREAD

**Issue by klkeys** [JuliaGPU/OpenCL.jl#85]
I am trying to use OpenCL.jl in a *k*-fold crossvalidation scheme. In this scheme, the GPU will house some data that are common to all *k* folds. I have a wrapper function that loads all of the data, allocates the (constant) GPU buffers, and compiles the OpenCL program/kernels. The wrapper then uses `@spawn` to farm each fold to its own CPU core. Each fold will then use the (constant) GPU data, plus some GPU buffers private to the fold.

When I tried to run this code, I ran into an unusual error:

    ERROR: LoadError: cannot serialize a pointer
    in serialize at serialize.jl:418
    in serialize at serialize.jl:127
    in serialize at serialize.jl:300
    in serialize at serialize.jl:418
    in send_msg_ at multi.jl:222
    in remotecall at multi.jl:710
    in remotecall at multi.jl:714
    ...

Something like this has arisen in other parallel computing schemes before; see https://github.com/JuliaLang/julia/issues/5954, https://github.com/JuliaOpt/NLopt.jl/issues/12, https://github.com/JuliaLang/julia/issues/3643.

I think that the problem is that the pointers to the GPU buffers are not automatically serialized. Is this difficult to do? I would do it myself, but I am clueless about what the serialization of a pointer actually means. :-(

**Comment by jakebolewski** [comment]
Can you provide a small test-case that is failing?  I'm not surprised this does not work as we would have to provide special serialization methods for OpenCL Buffers.  Do-able, but a test / use-case helps.

**Comment by klkeys** [comment]
I wrote a (somewhat verbose) minimal working example a public Gist: https://gist.github.com/klkeys/ff9e79e002e9a8f6cda4.
On my server with a Tesla C2050 GPU, it throws the error that I described earlier.

**Comment by jakebolewski** [comment]
That example does not work, but I see what you are trying to do.  I think first off you have to define a ctx / queue per process.  Once you have that  you should send the buffer's back at a high level using Julia's RPC mechanism.   Trying to share the queue over multiple processors is not going to work.

As for specific types serializing pointer's will no longer throw an error and instead will deserialize the pointer value to NULL on the calling / called process.  This should be available in 0.4.1 update and the latest Julia trunk.  This should be fine, but ideally you should be sharing *results* and not openCL object's which will only be valid for the process / ctx they are defined on.

**Comment by jakebolewski** [comment]
```julia
@everywhere module Foo
 
import OpenCL
const cl = OpenCL

# this kernel squares the entries of a buffer x and saves them into another buffer y
# n is the length of x and y
const mykernel =  "__kernel void square(__global float *y, __global float *x, const int n) {
    int i = get_global_id(0);
    if (i < n) {
        y[i] = x[i]*x[i];
    }
    return;
}
"

# one_fold() initializes a return array y and its corresponding GPU buffer
# it then executes the GPU kernel and copies the result from the device to the host array y
# finally, it returns the host array y
function one_fold(x_buff, square, ctx, device, queue; wg_size::Int = 512, n::Int = 100)
    y_buff = cl.Buffer(Float32, ctx, n)
    cl.wait(cl.call(queue, square, (wg_size,1,1), nothing, y_buff, x_buff, convert(Int32,n)))
    return cl.read(queue, y_buff)
end

# this function configures the GPU environment and spawns one_fold() on each CPU worker
# each CPU core executes one_fold() with access to a common device buffer x # each core will use x to execute a GPU kernel, save the result to a private device buffer,
# then copy back to a host array and return it
function test_gpu_serialization(n=100)
    nw     = nworkers()
    myrefs = cell(nw)
    sumsq  = zeros(Float32,n)
    for i = 1:nw
        myrefs[i] = remotecall(i) do
            device = last(cl.devices(:gpu))
            ctx    = cl.Context(device)
            queue  = cl.CmdQueue(ctx)
            x_buff = cl.Buffer(Float32, ctx, (:r,:copy), hostbuf=2.0*ones(Float32,n))
            prg    = cl.Program(ctx, source=mykernel) |> cl.build!
            kern   = cl.Kernel(prg, "square")
            one_fold(x_buff,kern,ctx,device,queue,n=n)
        end
    end
    for i = 1:nw
        sumsq += fetch(myrefs[i])
    end
    return sumsq ./ nw
end

end
```

**Comment by klkeys** [comment]
@jakebolewski this is wonderful! But there is one problem. In this framework, each process has its own copy of `x_buff`. If I have, say, `k = 10` processes, then there are 10 copies of the same data on the GPU. I will very quickly exceed GPU memory capacity if I execute this code. Is there no way for the master process to initialize `x_buff` once and then tell the processes to find it? That would allow all processes to use the same GPU.

**Comment by jakebolewski** [comment]
The buffer has to be local to each process.  You have to do the subdivision manually or come up with an abstraction that handles this for you.

**Comment by klkeys** [comment]
Understood. I will need to return to my drawing board and think about how to correctly distribute these computations. Thank you for your help @jakebolewski!
